/*
 * This source file was generated by the Gradle 'init' task
 */
package webgui;

import dev.selenium.page.DocumentationPage;
import dev.selenium.page.MainPage;
import org.framework.TestContext;
import org.junit.jupiter.api.Test;

class SomeTestScenario {

    @Test void someTestCase() {
        TestContext testContext = new TestContext();
        MainPage mainPage = new MainPage();
        mainPage.pressDocumentationButton(testContext);

        DocumentationPage documentationPage = new DocumentationPage();
        documentationPage.tableComponent.clickOnKotlinButton(testContext);
        documentationPage.searchComponent.clickOnSearchButton(testContext);
        documentationPage.searchComponent.inputTextToSearchField(testContext, "wait");
        documentationPage.searchComponent.clickResetButton(testContext);
        documentationPage.searchComponent.inputTextToSearchField(testContext, "explicit");
        documentationPage.searchComponent.clickFirstSearchHit(testContext);




        /** Zadanie:
         * Idz do https://www.selenium.dev/
         * Kliknij w Documentation z menu glownego
         * Na nowej stronie bedzie snippet z zakladkami, wybierz "kotlin"
         * U gory, w prawym gornym rogu jest wyszukiwanie - kliknij w nie
         * W oknie wyszukiwania wpisz "wait"
         * Nic nie klikaj tylko skasuj "wait" i wpisz "explicit"
         * Kliknij pierwszy element listy
         */


    }

}
