/*
 * This source file was generated by the Gradle 'init' task
 */
package webgui;

import dev.selenium.page.DocumentationPage;
import dev.selenium.page.ExplicitWaitPage;
import dev.selenium.page.MainPage;
import org.framework.TestContext;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SomeTestScenario {
    private TestContext testContext;
    private static final String TEXT = "fixed implicit wait javascript example (#1909)[deploy site] (680f75b07ed)";

    @BeforeEach
    public void init(){
        testContext = new TestContext();
    }

    @Test void someTestCase() {
        MainPage mainPage = new MainPage();
        mainPage.pressDocumentationButton(testContext);

        DocumentationPage documentationPage = new DocumentationPage();
        documentationPage.tableComponent.clickOnKotlinButton(testContext);
        documentationPage.searchComponent.clickOnSearchButton(testContext);
        documentationPage.searchComponent.inputTextToSearchField(testContext, "wait");
        documentationPage.searchComponent.clickResetButton(testContext);
        documentationPage.searchComponent.inputTextToSearchField(testContext, "explicit");
        documentationPage.searchComponent.clickFirstSearchHit(testContext);

        ExplicitWaitPage explicitWaitPage = new ExplicitWaitPage();
        String textFromFoundedTag = explicitWaitPage.getTextFromFoundedTag(testContext);
        assertEquals(textFromFoundedTag, TEXT);

    }

    @AfterEach
    public void teardown(){
        testContext.terdown();
    }

}
